### ISSUE TITLE
ValueError: Unsupported insert value type: <class 'dict'>

### ISSUE THREAD

**Issue by nieweiming** [frostming/Flog#30]
当我按照开发部署时，执行到 pdm sync -d  报错如下：

[AUTO-MIGRATION] Legacy pdm 0.x metadata detected, migrating to PEP 621...
Traceback (most recent call last):
  File "c:\users\vimin\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vimin\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Vimin\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "c:\users\vimin\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 184, in main
    return Core().main(args)
  File "c:\users\vimin\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 130, in main
    self.ensure_project(options, obj)
  File "c:\users\vimin\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 100, in ensure_project
    migrate_pyproject(options.project)
  File "c:\users\vimin\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 691, in migrate_pyproject
    do_import(project, str(project.pyproject_file), "legacy")
  File "c:\users\vimin\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 547, in do_import
    merge_dictionary(pyproject["tool"]["pdm"], settings)  # type: ignore
  File "c:\users\vimin\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\utils.py", line 509, in merge_dictionary
    target[key].extend(value)
  File "c:\users\vimin\appdata\local\programs\python\python39\lib\_collections_abc.py", line 1093, in extend
    self.append(v)
  File "c:\users\vimin\appdata\local\programs\python\python39\lib\_collections_abc.py", line 1072, in append
    self.insert(len(self), value)
  File "c:\users\vimin\.local\pipx\venvs\pdm\lib\site-packages\atoml\items.py", line 1348, in insert
    raise ValueError(f"Unsupported insert value type: {type(value)}")
ValueError: Unsupported insert value type: <class 'dict'>

OS: window10
python: 3.9
pdm：version 1.6.2

**Comment by frostming** [comment]
修复了这个问题，并且更新了wiki说明
