### ISSUE TITLE
No module named 'flask'`

### ISSUE THREAD

**Issue by Termset** [frostming/Flog#36]
为什么会提示没有flask呢
`web_1    | pdm.exceptions.PdmUsageError: Unsupported shell: sh, please specify another shell via `--pep582 <SHELL>`
web_1    | Traceback (most recent call last):
web_1    |   File "/app/__pypackages__/3.9/bin/flask", line 5, in <module>
web_1    |     from flask.cli import main
web_1    | ModuleNotFoundError: No module named 'flask'
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/bin/pdm", line 8, in <module>
web_1    |     sys.exit(main())
web_1    |   File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 219, in main
web_1    |     return Core().main(args)
web_1    |   File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 143, in main
web_1    |     print_pep582_command(self.ui, options.pep582)
web_1    |   File "/usr/local/lib/python3.9/site-packages/pdm/cli/actions.py", line 712, in print_pep582_command
web_1    |     raise PdmUsageError(
web_1    | pdm.exceptions.PdmUsageError: Unsupported shell: sh, please specify another shell via `--pep582 <SHELL>`
web_1    | Traceback (most recent call last):
web_1    |   File "/app/__pypackages__/3.9/bin/flask", line 5, in <module>
web_1    |     from flask.cli import main
web_1    | ModuleNotFoundError: No module named 'flask'`

**Comment by Termset** [comment]
已经拉取镜像成功了的
